### ISSUE TITLE
Unable to deploy MDA quickstart v2 due to S3 errors

### ISSUE THREAD

**Issue by awsmrud** [aws-quickstart/quickstart-aws-utility-meter-data-analytics-platform-v2#35]
Deploying the MDA v2 stack results in rollback due to multiple S3 errors:
https://aws-quickstart.github.io/quickstart-aws-utility-meter-data-analytics-platform-v2/

DataStorageStack: S3 error: The specified key does not exist. For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html

IntegrationStack: S3 error: The specified key does not exist.

CopyGlueScriptsStack: S3 error: The specified key does not exist.

Above errors for both MeterDataGenerator parameter 'Disabled' and 'Enabled' options.

Please advise on resolution.

**Comment by SaschaJanssen** [comment]
@awsmrud fixed. The MDA can now be deployed again. 
Many thanks for reporting.
