### ISSUE TITLE
Encountered Head End Simulator errors when deploying MDA v2 Quick Start

### ISSUE THREAD

**Issue by awsmrud** [aws-quickstart/quickstart-aws-utility-meter-data-analytics-platform-v2#39]
Using MDA v2 Quick Start to deploy stack:

https://aws-quickstart.github.io/quickstart-aws-utility-meter-data-analytics-platform-v2/#_deployment_options

Parameters: With Head End simulator enabled, 15 min, 1000 devices

Errors:
* The following resource(s) failed to create: [MeterreadingsDataflowStack, MeterDataGeneratorStack, WeatherDataflowStack, TopologyDataflowStack]. Rollback requested by user.
* Embedded stack arn:aws:cloudformation:us-east-1:xxxx:stack/aws-utility-meter-data-analytics-platform-v2-MeterDataGeneratorStack-DFG67HAIWD6O/2a47b780-c916-11ed-845b-126048cd0ebd was not successfully created: The following resource(s) failed to create: [HeadEndSystemSimulatorStack].

Please advise

**Comment by tbulding** [comment]
This issue has been resolved with the latest PR
